image: node:9.11.1

pages:
  cache:
    paths:
      - node_modules/

  script:
    - yarn install # npm install
    - yarn build # npm run docs:build
  artifacts:
    paths:
      - public
  only:
    - master
