name: "错误修正"
description: "发现文档内容有误并提交修正请求"
title: "[错误修正] <title>"
labels: ["错误/Mistakes"]
body:
  - type: checkboxes
    id: confirmations
    attributes:
      label: "提交前请确认"
      options:
        - label: "我已阅读贡献指南, 已确认文档中有错误存在，且 Issues、Pull Requests 中无相同修正"
          required: true
        - label: "我已验证修正内容的正确性"
          required: false

  - type: input
    id: document_link
    attributes:
      label: "错误所在文档链接"
      description: |
        需要修正的文档链接，指定到具体 API<br>
        eg: https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/bangumi/info.md#获取剧集明细web端ssidepid方式<br>
            https://socialsisteryi.github.io/bilibili-API-collect/docs/bangumi/info.html#获取剧集明细-web端-ssid-epid方式
    validations:
      required: true

  - type: dropdown
    id: error_type
    attributes:
      label: "错误类型"
      multiple: true
      options:
        - "API 地址/鉴权方式错误"
        - "参数错误"
        - "响应数据结构或响应示例错误"
        - "描述性内容错误（如拼写/流程说明）"
        - "接口已弃用或下线"
        - "其他（请在下文说明）"
    validations:
      required: true

  - type: textarea
    id: error_description
    attributes:
      label: "错误描述"
      description: "请详细说明具体错误所在，如有多个错误请编号列出"
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: "纠错依据"
      description: "如果有，请提供抓包记录等佐证，方便确认。如果有多个错误，请将依据对应错误描述的编号列出"
    validations:
      required: false

  - type: textarea
    id: correction
    attributes:
      label: "修正方案"
      description: "如果可以，请提供修正后的内容，如有多个修正点请编号列出"
    validations:
      required: false
